default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:
development:
  <<: *default
  database: 'base_development'
test:
  <<: *default
  database: 'base_test'
production:
  <<: *default
  database: base_production
