development: &defaults
  client_id: 579264015511837
  client_secret: 17358a19442095fbaa2ec86f769c454d
  scope: user_about_me,friends_about_me,user_activities,friends_activities,user_birthday,user_checkins,user_events,friends_events,user_hometown,friends_hometown,user_interests,friends_interests,user_likes,friends_likes,user_location,friends_location,user_notes,friends_notes,user_online_presence,friends_online_presence,user_status,friends_status,user_website,user_work_history,email
  canvas_url: https://apps.facebook.com/gooner-analytics

test:
  <<: *defaults

production:
  <<: *defaults
